// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChSoR5u5CcDeLvm0KqadXsWFmVBvcN5vg',
    appId: '1:74664026083:ios:d5c779b7efb0534a3b4ad6',
    messagingSenderId: '74664026083',
    projectId: 'studbank',
    storageBucket: 'studbank.firebasestorage.app',
    iosBundleId: 'com.example.studbank',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXgLlhF8d4diVkPV_CJ09KyAwMKZRkzdQ',
    appId: '1:74664026083:web:64333082161d56423b4ad6',
    messagingSenderId: '74664026083',
    projectId: 'studbank',
    authDomain: 'studbank.firebaseapp.com',
    storageBucket: 'studbank.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChSoR5u5CcDeLvm0KqadXsWFmVBvcN5vg',
    appId: '1:74664026083:ios:d5c779b7efb0534a3b4ad6',
    messagingSenderId: '74664026083',
    projectId: 'studbank',
    storageBucket: 'studbank.firebasestorage.app',
    iosBundleId: 'com.example.studbank',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH7Qwj9bh6roYVgAcweJFwAYte7LCLTjs',
    appId: '1:74664026083:android:350a21fa532e56af3b4ad6',
    messagingSenderId: '74664026083',
    projectId: 'studbank',
    storageBucket: 'studbank.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXgLlhF8d4diVkPV_CJ09KyAwMKZRkzdQ',
    appId: '1:74664026083:web:4c64739e6321a6523b4ad6',
    messagingSenderId: '74664026083',
    projectId: 'studbank',
    authDomain: 'studbank.firebaseapp.com',
    storageBucket: 'studbank.firebasestorage.app',
  );

}