# File: momo-proxy/wrangler.toml

name = "momo-proxy"
main = "src/index.js"
compatibility_date = "2025-07-24"

[vars]
MOMO_API_USER_ID = "c00150b6-07d7-4d83-b71d-5be9a855a2a1"
MOMO_API_KEY = "7ce2922beccb418e914db324003d33ed"
MOMO_SUBSCRIPTION_KEY = "2c28040e2be54efb94a6d8d16b7ecc92"
MOMO_BASEURL = "https://sandbox.momodeveloper.mtn.com"         # ← ADD this
MOMO_TOKENENDPOINT = "/collection/token/"                       # ← ADD this
